name: 'Edge Deploy CI (Maven)'

on:
  push:
    branches: [ master ]

env:
  DEFAULT_MUSIC_FOLDER: /tmp/music
  EXCLUDED_TEST_GROUPS:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - run: mkdir -p ${DEFAULT_MUSIC_FOLDER}
      - name: Build with Maven
        run: mvn -DexcludedGroups=${EXCLUDED_TEST_GROUPS} -Ddocker.testing.default-music-folder=${DEFAULT_MUSIC_FOLDER} verify -B -P integration-test
      - name: Calculate tags
        if: success()
        id: tagcalc
        run: >
          # Create tag
          ver=$(grep "version=" airsonic-main/target/generated/build-metadata/build.properties | cut -d"=" -f2);
          ts=$(grep "timestamp=" airsonic-main/target/generated/build-metadata/build.properties | cut -d"=" -f2);
          # Note this doesn't completely follow semver because docker tags do not take a + sign
          tag=$ver\.$ts
          echo $tag
          echo ::set-output name=tag::$tag
      - name: Deploy to GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tagcalc.outputs.tag }}
          name: Edge Release ${{ steps.tagcalc.outputs.tag }}
          draft: false
          prerelease: true
          files: |
            airsonic-main/target/airsonic.war
            airsonic-main/target/artifacts-checksums.sha
      - name: Tag Docker Images
        run: >
          # Tag the docker image
          docker tag airsonicadvanced/airsonic-advanced:latest airsonicadvanced/airsonic-advanced:edge-${{ steps.tagcalc.outputs.tag }};
          docker tag airsonicadvanced/airsonic-advanced:latest airsonicadvanced/airsonic-advanced:edge-latest;
          docker tag airsonicadvanced/airsonic-advanced:latest airsonicadvanced/airsonic-advanced:gitcommit-${{ github.sha }};
          docker tag airsonicadvanced/airsonic-advanced:latest airsonicadvanced/airsonic-advanced:gitrun-${{ github.run_id }};
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Deploy to DockerHub
        run: >
          docker push airsonicadvanced/airsonic-advanced:latest;
          docker push airsonicadvanced/airsonic-advanced:edge-latest;
          docker push airsonicadvanced/airsonic-advanced:edge-${{ steps.tagcalc.outputs.tag }};
          docker push airsonicadvanced/airsonic-advanced:gitcommit-${{ github.sha }};
          docker push airsonicadvanced/airsonic-advanced:gitrun-${{ github.run_id }};
